import { Button } from "std-widgets.slint";

component ValidatableLogo inherits Rectangle {
  in-out property<image> logo;
  in-out property<bool> is-valid;
  
  background: darkorange;
  states [
    valid when is-valid : {
      background: darkgreen;
      out {
        animate * { duration: 500ms; }
      }
      in {
        animate * { duration: 500ms; }
      }
    }
  ]

  Image {
    width: parent.width;
    height: parent.height;
    source: logo;
  }
}

export component AppPathsBar inherits Rectangle {
  in-out property<image> steam-logo;
  in-out property<image> rf2-logo;
  in-out property<bool> steam-valid;
  in-out property<bool> rf2-valid;

  height: 50px;

  HorizontalLayout {
    spacing: 10px;
    padding: 10px;
    ValidatableLogo {
      height: 40px;
      width: 40px;
      logo: steam-logo;
      is-valid: steam-valid;
    }
    ValidatableLogo {
      height: 40px;
      width: 40px;
      logo: rf2-logo;
      is-valid: rf2-valid;
    }
    Button {
      width: 100px;
      text: "Set Paths";
      clicked => { root.clicked() }
    }
  }

  callback clicked;
}
