[package]
name = "rf2_league_creator"
version = "0.0.1"
edition = "2021"

[dependencies]
automod = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.0.4"
getopts = "0.2.21"
pretty_assertions = "1.4.0"
