import { Button, VerticalBox , LineEdit} from "std-widgets.slint";
import { FilePathSelection } from "components/file-selection.slint";

export component Demo inherits Window {
  property<brush> b2: Colors.red;
  preferred-width: 1000px;
  preferred-height: 500px;
  padding: 10px;
  background: black;
    ws-select := FilePathSelection{
        y: 10px;
        x: 10px;
        width: 980px;
        label: "Path of rF2 ModMgr.exe";
        text-accepted(s) => {
            root.ws-text-accepted(s);
        }
        choose-click => {
            root.ws-choose-dir();
        }
    }
  rect := Rectangle {

    y: 600px;
    x: 10px;
    width: 900px;
    height: 50px;
    background: darkorange;
    border-radius: 15px;
    val := LineEdit {
        x: 10px;
        width: 220px;
    }
    Button {
        x: 240px;
        width: 150px;
        text: "Choose Directory";
        clicked => {
            rect.background = b2;
            root.choose-dir()
        }
    }
  }


    callback ws-text-accepted(string);

    
    callback ws-change-text(string);
    ws-change-text(s) => {
        val.text = s;
        root.background = Colors.darkorange
    }
    callback ws-validate-text;
    ws-validate-text => { root.background = Colors.darkgreen }
    
    callback ws-choose-dir;
    callback change-dir(string);
    change-dir(d) => { rect.background = Colors.darkorange; }
    callback validate-dir;
    callback dir-validated;
    dir-validated() => { rect.background = Colors.darkgreen }
}
