import { Button, VerticalBox , LineEdit} from "std-widgets.slint";
import { FilePathSelection } from "components/file-selection.slint";
import { WorkshopPathController } from "controller/workshop-path.slint";
import { Rfactor2PathController } from "controller/rfactor2-path.slint";
import { AppPathsBar } from "app-paths-bar.slint";

export { WorkshopPathController, Rfactor2PathController }

export global Images {
  in-out property <image> steam;
  in-out property <image> rfactor2;
}

export component Main inherits Window {
  property<string> mgr-path: "";

  preferred-width: 1000px;
  preferred-height: 500px;
  padding: 10px;
  background: black;
  AppPathsBar { 
    y:0;
    x:0;
    width: 100%;
    height: 50px;
    steam-logo: Images.steam;
    rf2-logo: Images.rfactor2;
  }
}
