name: Build and Deploy
on:
  push:
    branches:
      - main
      - 'ci_test/**'

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin -p rf2_league_creator -o Lcov
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build_cli:
    name: build CLI
    needs: coverage_report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: rustup target add x86_64-pc-windows-gnu
      - run: cargo install cargo-zigbuild
      - run: cargo zigbuild --release --target x86_64-pc-windows-gnu -p rf2_league_creator
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: rfactor2-mod-tool-cli
          path: target/x86_64-pc-windows-gnu/release/rfactor2_league_mod_tool_cli.exe

#  build_gui:
#    name: build GUI
#    needs: coverage_report
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: korandoru/setup-zig@v1
#        with:
#          zig-version: 0.10.1
#      - uses: actions-rust-lang/setup-rust-toolchain@v1
#      - run: rustup target add x86_64-pc-windows-gnu
#      - run: cargo install cargo-zigbuild
#      - run: cargo zigbuild --release --target x86_64-pc-windows-gnu -p rf2_league_tool
